cd /t3home/fglessge/CMSSW_10_1_0/src/Xbb/python/
Task: sysnew
Pwd: /t3home/fglessge/CMSSW_10_1_0/src/Xbb/python
Host: t3wn53
User: fglessge
StartTime: 2022-02-21 10:09:23

Parsing files in Zll2017config...

python ./sys_new.py --addCollections Sys.boostedFlags --fileList base64:eNolx70KwjAUQOEnqvcmTYyddSjSikMpOIX83DaCNiFJB99e0LN8HCg1ZoI1xz1BCp+iw3NdCwRrYat7elGBubf2Hku9mS0CR6ZgZgwujyvVMsVh0GMjUfdTIxBrPCLqad/ofJeatRPNzdv4NZsUxmFs0qeGpzkBtwKR2VYY55BapbyTTDg0Xi7LSbFOOMbF4jh13hLvjBPopPKAv/Sf30HNRFodcoz1C8UzQII= --sampleIdentifier DYJetsToLL_M-50_HT-400to600_TuneCP5_13TeV-madgraphMLM-pythia8 --config /t3home/fglessge/CMSSW_10_1_0/src//Xbb/python/logs_Zll2017//boost/config//submission_20220221_100817.ini --inputDir BOOSTin --outputDir BOOSTout
Error in <TNetXNGFile::Open>: [ERROR] Server responded with an error: [3011] No such file

len(filelist) 1 filelist[0]: /store/group/phys_higgs/hbb/ntuples/VHbbPostNano/2017/V11/DYJetsToLL_M-50_HT-400to600_TuneCP5_13TeV-madgraphMLM-pythia8/2b4001b34acc0e377dc514c0ad5ff87194c124fc2e9dbe29ac40c57d/000000_000000/0000/tree_7.root
INput samples:	root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/kinfit_out
OUTput samples:	root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/boost
collections to add: ['Sys.boostedFlags']
after parsing: ['VHbbCommon.isBoosted', 'VHbbCommon.isBoostedVZ']
INFO: reading part  1  of  1
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_USER_PROXY = /t3home/fglessge/.x509up_u742
INFO: file was not found:root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/kinfit_out/DYJetsToLL_M-50_HT-400to600_TuneCP5_13TeV-madgraphMLM-pythia8/tree_2b4001b34acc0e377dc514c0ad5ff87194c124fc2e9dbe29ac40c57d_000000_000000_0000_7_ef6b0040765d81dc19c102e4f2f530be14c21bc133b6d56c2e938d45.root, trying 2 more times...
INFO: wait 1 seconds before trying again
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_USER_PROXY = /t3home/fglessge/.x509up_u742
INFO: file was not found:root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/kinfit_out/DYJetsToLL_M-50_HT-400to600_TuneCP5_13TeV-madgraphMLM-pythia8/tree_2b4001b34acc0e377dc514c0ad5ff87194c124fc2e9dbe29ac40c57d_000000_000000_0000_7_ef6b0040765d81dc19c102e4f2f530be14c21bc133b6d56c2e938d45.root, trying 1 more times...
INFO: wait 2 seconds before trying again
[31mERROR: file is missing: root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/kinfit_out/DYJetsToLL_M-50_HT-400to600_TuneCP5_13TeV-madgraphMLM-pythia8/tree_2b4001b34acc0e377dc514c0ad5ff87194c124fc2e9dbe29ac40c57d_000000_000000_0000_7_ef6b0040765d81dc19c102e4f2f530be14c21bc133b6d56c2e938d45.root[0m
INFO: # files chained: 0
trying fallback... 1
FO: root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/kinfit_out//store/group/phys_higgs/hbb/ntuples/VHbbPostNano/2017/V11/DYJetsToLL_M-50_HT-400to600_TuneCP5_13TeV-madgraphMLM-pythia8/2b4001b34acc0e377dc514c0ad5ff87194c124fc2e9dbe29ac40c57d/000000_000000/0000/tree_7.root
INFO: reading part  1  of  1
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_USER_PROXY = /t3home/fglessge/.x509up_u742
INFO: file was not found:root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/kinfit_out//store/group/phys_higgs/hbb/ntuples/VHbbPostNano/2017/V11/DYJetsToLL_M-50_HT-400to600_TuneCP5_13TeV-madgraphMLM-pythia8/2b4001b34acc0e377dc514c0ad5ff87194c124fc2e9dbe29ac40c57d/000000_000000/0000/tree_7.root, trying 2 more times...
INFO: wait 1 seconds before trying again
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_USER_PROXY = /t3home/fglessge/.x509up_u742
INFO: file was not found:root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/kinfit_out//store/group/phys_higgs/hbb/ntuples/VHbbPostNano/2017/V11/DYJetsToLL_M-50_HT-400to600_TuneCP5_13TeV-madgraphMLM-pythia8/2b4001b34acc0e377dc514c0ad5ff87194c124fc2e9dbe29ac40c57d/000000_000000/0000/tree_7.root, trying 1 more times...
INFO: wait 2 seconds before trying again
[31mERROR: file is missing: root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/kinfit_out//store/group/phys_higgs/hbb/ntuples/VHbbPostNano/2017/V11/DYJetsToLL_M-50_HT-400to600_TuneCP5_13TeV-madgraphMLM-pythia8/2b4001b34acc0e377dc514c0ad5ff87194c124fc2e9dbe29ac40c57d/000000_000000/0000/tree_7.root[0m
INFO: # files chained: 0
[31mERROR: file does not exist or is broken, will be SKIPPED![0m
Traceback (most recent call last):
  File "./sys_new.py", line 301, in <module>
    xr.run()
  File "./sys_new.py", line 281, in run
    raise Exception("ProcessingIncomplete")
Exception: ProcessingIncomplete
--------------------------------------------------------------------------------
exit code: 1
EndTime: 2022-02-21 10:09:48
duration (real time): 0 minutes
--- RETRY ---
python ./sys_new.py --addCollections Sys.boostedFlags --fileList base64:eNolx70KwjAUQOEnqvcmTYyddSjSikMpOIX83DaCNiFJB99e0LN8HCg1ZoI1xz1BCp+iw3NdCwRrYat7elGBubf2Hku9mS0CR6ZgZgwujyvVMsVh0GMjUfdTIxBrPCLqad/ofJeatRPNzdv4NZsUxmFs0qeGpzkBtwKR2VYY55BapbyTTDg0Xi7LSbFOOMbF4jh13hLvjBPopPKAv/Sf30HNRFodcoz1C8UzQII= --sampleIdentifier DYJetsToLL_M-50_HT-400to600_TuneCP5_13TeV-madgraphMLM-pythia8 --config /t3home/fglessge/CMSSW_10_1_0/src//Xbb/python/logs_Zll2017//boost/config//submission_20220221_100817.ini --inputDir BOOSTin --outputDir BOOSTout
Error in <TNetXNGFile::Open>: [ERROR] Server responded with an error: [3011] No such file

len(filelist) 1 filelist[0]: /store/group/phys_higgs/hbb/ntuples/VHbbPostNano/2017/V11/DYJetsToLL_M-50_HT-400to600_TuneCP5_13TeV-madgraphMLM-pythia8/2b4001b34acc0e377dc514c0ad5ff87194c124fc2e9dbe29ac40c57d/000000_000000/0000/tree_7.root
INput samples:	root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/kinfit_out
OUTput samples:	root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/boost
collections to add: ['Sys.boostedFlags']
after parsing: ['VHbbCommon.isBoosted', 'VHbbCommon.isBoostedVZ']
INFO: reading part  1  of  1
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_USER_PROXY = /t3home/fglessge/.x509up_u742
INFO: file was not found:root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/kinfit_out/DYJetsToLL_M-50_HT-400to600_TuneCP5_13TeV-madgraphMLM-pythia8/tree_2b4001b34acc0e377dc514c0ad5ff87194c124fc2e9dbe29ac40c57d_000000_000000_0000_7_ef6b0040765d81dc19c102e4f2f530be14c21bc133b6d56c2e938d45.root, trying 2 more times...
INFO: wait 1 seconds before trying again
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_USER_PROXY = /t3home/fglessge/.x509up_u742
INFO: file was not found:root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/kinfit_out/DYJetsToLL_M-50_HT-400to600_TuneCP5_13TeV-madgraphMLM-pythia8/tree_2b4001b34acc0e377dc514c0ad5ff87194c124fc2e9dbe29ac40c57d_000000_000000_0000_7_ef6b0040765d81dc19c102e4f2f530be14c21bc133b6d56c2e938d45.root, trying 1 more times...
INFO: wait 2 seconds before trying again
[31mERROR: file is missing: root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/kinfit_out/DYJetsToLL_M-50_HT-400to600_TuneCP5_13TeV-madgraphMLM-pythia8/tree_2b4001b34acc0e377dc514c0ad5ff87194c124fc2e9dbe29ac40c57d_000000_000000_0000_7_ef6b0040765d81dc19c102e4f2f530be14c21bc133b6d56c2e938d45.root[0m
INFO: # files chained: 0
trying fallback... 1
FO: root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/kinfit_out//store/group/phys_higgs/hbb/ntuples/VHbbPostNano/2017/V11/DYJetsToLL_M-50_HT-400to600_TuneCP5_13TeV-madgraphMLM-pythia8/2b4001b34acc0e377dc514c0ad5ff87194c124fc2e9dbe29ac40c57d/000000_000000/0000/tree_7.root
INFO: reading part  1  of  1
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_USER_PROXY = /t3home/fglessge/.x509up_u742
INFO: file was not found:root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/kinfit_out//store/group/phys_higgs/hbb/ntuples/VHbbPostNano/2017/V11/DYJetsToLL_M-50_HT-400to600_TuneCP5_13TeV-madgraphMLM-pythia8/2b4001b34acc0e377dc514c0ad5ff87194c124fc2e9dbe29ac40c57d/000000_000000/0000/tree_7.root, trying 2 more times...
INFO: wait 1 seconds before trying again
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_USER_PROXY = /t3home/fglessge/.x509up_u742
INFO: file was not found:root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/kinfit_out//store/group/phys_higgs/hbb/ntuples/VHbbPostNano/2017/V11/DYJetsToLL_M-50_HT-400to600_TuneCP5_13TeV-madgraphMLM-pythia8/2b4001b34acc0e377dc514c0ad5ff87194c124fc2e9dbe29ac40c57d/000000_000000/0000/tree_7.root, trying 1 more times...
INFO: wait 2 seconds before trying again
[31mERROR: file is missing: root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/kinfit_out//store/group/phys_higgs/hbb/ntuples/VHbbPostNano/2017/V11/DYJetsToLL_M-50_HT-400to600_TuneCP5_13TeV-madgraphMLM-pythia8/2b4001b34acc0e377dc514c0ad5ff87194c124fc2e9dbe29ac40c57d/000000_000000/0000/tree_7.root[0m
INFO: # files chained: 0
[31mERROR: file does not exist or is broken, will be SKIPPED![0m
Traceback (most recent call last):
  File "./sys_new.py", line 301, in <module>
    xr.run()
  File "./sys_new.py", line 281, in run
    raise Exception("ProcessingIncomplete")
Exception: ProcessingIncomplete
exit code: 1
duration (real time): 0 minutes, including retry

Exiting runAll.sh

